CREATE DATABASE IF NOT EXISTS test1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE test1;

DROP TABLE IF EXISTS person, data, mapping;

CREATE TABLE person (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100)
);

CREATE TABLE data (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  data VARCHAR(50)
);

CREATE TABLE mapping (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  person_id INT,
  data_id INT
);
